import Head from "next/head";
import {Geist, Geist_Mono} from "next/font/google";
import styles from "@/styles/Home.module.css";
import {useCharacters} from "@/assets/hooks/useCharacters";
import {CharactersCard} from "@/components/CharactersCard";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export default function Home() {

    const characters = useCharacters()

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div
                className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
            >
                <main className={styles.main}>
                    {characters && characters.map((char) => (

                        <CharactersCard key={char.id} character={char}/>
                    ))}
                </main>
            </div>
        </>
    );
}



